services:
  web:
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
      - /var/run/docker.sock:/var/run/docker.sock   
    depends_on:
      - db

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: dictionary
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - "8082:80"
    environment:
      PMA_ARBITRARY: 1
    depends_on:
      - db
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock  

volumes:
  db_data:
